local install = vim.fn["plug#"]

vim.call("plug#begin")

install("aspeddro/gitui.nvim") -- Currently the main git plugin.
install("kdheepak/lazygit.nvim") -- The alternative to gitui.
install("3rd/image.nvim")
install("BurntSushi/ripgrep")
install("L3MON4D3/LuaSnip")
install("MunifTanjim/nui.nvim")
install("NvChad/nvim-colorizer.lua")
install("SmiteshP/nvim-navbuddy")
install("SmiteshP/nvim-navic")
install("ahmedkhalf/project.nvim")
install("akinsho/bufferline.nvim")
install("danymat/neogen")
install("folke/lsp-colors.nvim")
install("folke/neodev.nvim")
install("folke/trouble.nvim")
install("folke/which-key.nvim")
install("github/copilot.vim")
install("goolord/alpha-nvim")
install("hrsh7th/cmp-buffer")
install("hrsh7th/cmp-cmdline")
install("hrsh7th/cmp-nvim-lsp")
install("hrsh7th/cmp-path")
install("hrsh7th/nvim-cmp")
install("iamcco/markdown-preview.nvim")
install("j-hui/fidget.nvim")
install("kevinhwang91/nvim-ufo")
install("kevinhwang91/promise-async")
install("lukas-reineke/indent-blankline.nvim")
install("mfussenegger/nvim-dap")
install("morhetz/gruvbox")
install("neovim/nvim-lspconfig")
install("numToStr/Comment.nvim")
install("nvim-lua/plenary.nvim")
install("nvim-lualine/lualine.nvim")
install("nvim-neo-tree/neo-tree.nvim")
install("nvim-telescope/telescope-ui-select.nvim")
install("nvim-telescope/telescope.nvim")
install("nvim-tree/nvim-web-devicons")
install("nvim-treesitter/nvim-treesitter")
install("rafamadriz/friendly-snippets")
install("ray-x/lsp_signature.nvim")
install("rcarriga/nvim-dap-ui")
install("rcarriga/nvim-notify")
install("saadparwaiz1/cmp_luasnip")
install("stevearc/conform.nvim")
install("stevearc/dressing.nvim")
install("williamboman/mason-lspconfig.nvim")
install("williamboman/mason.nvim")
install("windwp/nvim-autopairs")
install("indrets/diffview.nvim")
install("akinsho/toggleterm.nvim")
install("sindrets/diffview.nvim")
install("paopaol/telescope-git-diffs.nvim")
install("davvid/telescope-git-grep.nvim")

vim.call("plug#end")

require("options")
require("plugins")
require("mappings")
