local mod = vim.fn["plug#"]

vim.call("plug#begin")

mod("ibhagwan/fzf-lua")
mod("3rd/image.nvim")
mod("L3MON4D3/LuaSnip")
mod("MunifTanjim/nui.nvim")
mod("NeogitOrg/neogit")
mod("NvChad/nvim-colorizer.lua")
mod("SmiteshP/nvim-navbuddy")
mod("SmiteshP/nvim-navic")
mod("Wansmer/treesj")
mod("ahmedkhalf/project.nvim")
mod("akinsho/bufferline.nvim")
mod("danymat/neogen")
mod("folke/neodev.nvim")
mod("folke/noice.nvim")
mod("folke/todo-comments.nvim")
mod("folke/trouble.nvim")
mod("folke/which-key.nvim")
mod("folke/zen-mode.nvim")
mod("github/copilot.vim")
mod("goolord/alpha-nvim")
mod("hrsh7th/cmp-buffer")
mod("hrsh7th/cmp-calc")
mod("hrsh7th/cmp-cmdline")
mod("hrsh7th/cmp-nvim-lsp")
mod("hrsh7th/cmp-path")
mod("hrsh7th/nvim-cmp")
mod("j-hui/fidget.nvim")
mod("kylechui/nvim-surround")
mod("ldelossa/nvim-ide")
mod("lewis6991/gitsigns.nvim")
mod("lukas-reineke/indent-blankline.nvim")
mod("mfussenegger/nvim-dap")
mod("neovim/nvim-lspconfig")
mod("numToStr/Comment.nvim")
mod("nvim-lua/plenary.nvim")
mod("nvim-lualine/lualine.nvim")
mod("nvim-neo-tree/neo-tree.nvim")
mod("nvim-telescope/telescope-fzf-native.nvim")
mod("nvim-telescope/telescope.nvim")
mod("nvim-tree/nvim-web-devicons")
mod("nvimdev/lspsaga.nvim")
mod("nvimtools/none-ls.nvim")
mod("onsails/lspkind.nvim")
mod("projekt0n/github-nvim-theme")
mod("rafamadriz/friendly-snippets")
mod("rcarriga/nvim-dap-ui")
mod("rcarriga/nvim-notify")
mod("saadparwaiz1/cmp_luasnip")
mod("stevearc/conform.nvim")
mod("williamboman/mason-lspconfig.nvim")
mod("windwp/nvim-autopairs")
mod("windwp/nvim-ts-autotag")

mod("nvim-treesitter/nvim-treesitter", {
	["do"] = function()
		vim.cmd("TSUpdate")
	end,
})

mod("williamboman/mason.nvim", {
	["do"] = function()
		vim.cmd("MasonUpdate")
	end,
})

vim.call("plug#end")
