local mod = vim.fn["plug#"]

vim.call("plug#begin")

mod("3rd/image.nvim")
mod("MunifTanjim/nui.nvim")
mod("NeogitOrg/neogit")
mod("NvChad/nvim-colorizer.lua")
mod("SmiteshP/nvim-navic")
mod("Wansmer/treesj")
mod("akinsho/bufferline.nvim")
mod("danymat/neogen")
mod("folke/noice.nvim")
mod("folke/todo-comments.nvim")
mod("folke/trouble.nvim")
mod("folke/which-key.nvim")
mod("goolord/alpha-nvim")
mod("hrsh7th/cmp-buffer")
mod("hrsh7th/cmp-cmdline")
mod("hrsh7th/cmp-path")
mod("hrsh7th/nvim-cmp")
mod("j-hui/fidget.nvim")
mod("kylechui/nvim-surround")
mod("lukas-reineke/indent-blankline.nvim")
mod("mfussenegger/nvim-dap")
mod("ms-jpq/coq.artifacts")
mod("ms-jpq/coq.thirdparty")
mod("ms-jpq/coq_nvim", { ["do"] = function() vim.cmd(":COQdeps<cr>") end })
mod("neovim/nvim-lspconfig")
mod("numToStr/Comment.nvim")
mod("nvim-lua/plenary.nvim")
mod("nvim-lualine/lualine.nvim")
mod("nvim-neo-tree/neo-tree.nvim")
mod("nvim-telescope/telescope.nvim")
mod("nvim-tree/nvim-web-devicons")
mod("nvim-treesitter/nvim-treesitter")
mod("nvimdev/lspsaga.nvim")
mod("rcarriga/nvim-dap-ui")
mod("rcarriga/nvim-notify")
mod("stevearc/conform.nvim")
mod("williamboman/mason-lspconfig.nvim")
mod("williamboman/mason.nvim", { ["do"] = function() vim.cmd(":MasonUpdate<cr>") end })
mod("windwp/nvim-autopairs")
mod("windwp/nvim-ts-autotag")
mod("projekt0n/github-nvim-theme")
mod("github/copilot.vim")
mod("folke/neodev.nvim")

vim.call("plug#end")
